# 主程序运行配置
gesture_sequences:
  lock_screen: ["fist", "open_palm", "fist"]
  take_screenshot: ["peace", "thumbs_up"]
  volume_up: ["thumbs_up", "thumbs_up"]
  manual_control: [
      "open_palm",
      "open_palm",
      "open_palm",
      "open_palm",
      "open_palm",
    ] # 新增手动控制开关手势

detection:
  min_confidence: 0.7
  max_hands: 2
